WebApplication/Controllers/BookController.cs
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AbstractBLL;
using AutoMapper;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookLogic _bookLogic;
        private readonly IPublishingHouseLogic _publishingHouseLogic;
        private readonly IAuthorLogic _authorLogic;
        private readonly IAuthorsAndBooksLogic _authorsAndBooksLogic;
        private readonly IListGenreLogic _listGenreLogic;
        private readonly IGenreLogic _genreLogic;
        
        private readonly IMapper _mapper;

        public BookController(IBookLogic bookLogic, IPublishingHouseLogic publishingHouseLogic,
            IAuthorLogic authorLogic, IAuthorsAndBooksLogic authorsAndBooksLogic, IListGenreLogic listGenreLogic,
            IGenreLogic genreLogic, IMapper mapper)
        {
            _bookLogic = bookLogic;
            _publishingHouseLogic = publishingHouseLogic;
            _authorLogic = authorLogic;
            _authorsAndBooksLogic = authorsAndBooksLogic;
            _listGenreLogic = listGenreLogic;
            _genreLogic = genreLogic;
            _mapper = mapper;  
        }

        public BookController()
        {
        }

        public ActionResult AllBooks()
        {
            ViewData["ph"] = _mapper.Map<List<PublishingHouseModel>>(_publishingHouseLogic.GetAll());
            return View(_mapper.Map<List<BookModel>>(_bookLogic.GetAll()));
        }

        public ActionResult AddBook()
        {
            string title = Request.Form["title"];
            int year = Convert.ToInt32(Request.Form["year"]);
            int ph = Convert.ToInt32(_publishingHouseLogic.GetAll().Find(house => house.PublishingHouseTitle == Request.Form["ph"]).PublishingHouseID);
            string language = Request.Form["language"];
            _bookLogic.Create(new Book(title, year, ph, language));
            return RedirectToAction("AllBooks");
        }

        public ActionResult DeleteBook(int bookId)
        {
            _bookLogic.Delete(bookId);
            return RedirectToAction("AllBooks");
        }

        public ActionResult GetBook(int bookId)
        {
            Book book = _bookLogic.GetById(bookId);
            List<AuthorsAndBooks> authorId = _authorsAndBooksLogic.GetAll().FindAll(ab => ab.BookID == bookId);
            List<Author> authors = _authorLogic.GetAll().FindAll(a => authorId.Exists(ab => ab.AuthorID == a.AuthorID));
            List<ListGenre> listGenres = _listGenreLogic.GetAll().FindAll(lg => lg.BookID == bookId);
            List<Genre> genres = _genreLogic.GetAll().FindAll(g => listGenres.Exists(lg => lg.GenreID == g.GenreID));
            ViewData["ph"] = _publishingHouseLogic.GetAll().Find(p => p.PublishingHouseID == book.PublishingHouseID)
                .PublishingHouseTitle;
            ViewData["author"] = string.Join(", ", authors.Select(a => a.AuthorFullName).ToArray());
            ViewData["genre"] = string.Join(", ", genres.Select(g => g.GenreTitle).ToArray());
            ;
            return View(_mapper.Map<BookModel>(book));
        }
    }
}

WebApplication/Controllers/ReaderController.cs
using System.Collections.Generic;
using System.Web.Mvc;
using AbstractBLL;
using AutoMapper;
using Entities;
using ReadersBLL;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class ReaderController : Controller
    {
        private readonly IReadersLogic _readersLogic;
        
        private readonly IMapper _mapper;

        public ReaderController(IReadersLogic readersLogic, IMapper mapper)
        {
            _readersLogic = readersLogic;
            _mapper = mapper;  
        }

        public ReaderController()
        {
        }

        public ActionResult AllReaders()
        {
            var readers = _readersLogic.GetAll();
            return View(_mapper.Map<List<ReadersModel>>(readers));
        }

        public ActionResult GetReader(int libraryCard)
        {
            var reader = _readersLogic.GetById(libraryCard);
            return View (_mapper.Map<ReadersModel>(reader));
        }

        public ActionResult DeleteReader(int libraryCard)
        {
            _readersLogic.Delete(libraryCard);
            return RedirectToAction("AllReaders");
        }

        public ActionResult AddReader(string fullName, int age, string address)
        {
            _readersLogic.Create(new Readers(fullName, age, address));
            return RedirectToAction("AllReaders");
        }
    }
}

WebApplication/Views/Shared/_Layout.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand">
            Библиотека
        </span>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Выход", "Index", "Home", new {}, new {@class = "btn btn-success"})
                </li>
            </ul>
            <span class="navbar-text">
                @TempData.Peek("login")
            </span>
        </div>
    </nav>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.2020 - Rogova Nataliya</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")
@RenderSection("scripts", required: false)
</body>
</html>

WebApplication/Views/Shared/_LayoutAdmin.cshtml
<!DOCTYPE html>
<html>
<head>
    <meta charset="utf-8"/>
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <title>@ViewBag.Title</title>
    @Styles.Render("~/Content/css")
    @Scripts.Render("~/bundles/modernizr")
</head>
<body>
<div class="container">
    <nav class="navbar navbar-expand-lg navbar-light bg-light">
        <span class="navbar-brand">
            Библиотека
        </span>
        <div class="collapse navbar-collapse" id="navbarText">
            <ul class="navbar-nav mr-auto">
                <li class="nav-item active">
                    @Html.ActionLink("Выход", "Index", "Home", new {}, new {@class = "btn btn-success"})
                </li>
                <li class="nav-item active">
                    @Html.ActionLink("Главная", "AllReaders", "Reader", new {}, new {@class = "btn btn-success"})
                </li>
            </ul>
            <span class="navbar-brand">
                @Html.ActionLink("Книги", "AllBooks", "Book", new {}, new {@class = "btn btn-success"})
            </span>
            <span class="navbar-text">
                Администратор
            </span>
        </div>
    </nav>
</div>
<div class="container body-content">
    @RenderBody()
    <hr/>
    <footer>
        <p>&copy; @DateTime.Now.2020 - Rogova Nataliya</p>
    </footer>
</div>

@Scripts.Render("~/bundles/jquery")
@Scripts.Render("~/bundles/bootstrap")


@RenderSection("scripts", required: false)
</body>
</html>