WebApplication/Controllers/BookController.cs
using Entities;
using System;
using System.Collections.Generic;
using System.Linq;
using System.Web.Mvc;
using AbstractBLL;
using AutoMapper;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class BookController : Controller
    {
        private readonly IBookLogic _bookLogic;
        private readonly IPublishingHouseLogic _publishingHouseLogic;
        private readonly IAuthorLogic _authorLogic;
        private readonly IAuthorsAndBooksLogic _authorsAndBooksLogic;
        private readonly IListGenreLogic _listGenreLogic;
        private readonly IGenreLogic _genreLogic;
        
        private readonly IMapper _mapper;

        public BookController(IBookLogic bookLogic, IPublishingHouseLogic publishingHouseLogic,
            IAuthorLogic authorLogic, IAuthorsAndBooksLogic authorsAndBooksLogic, IListGenreLogic listGenreLogic,
            IGenreLogic genreLogic, IMapper mapper)
        {
            _bookLogic = bookLogic;
            _publishingHouseLogic = publishingHouseLogic;
            _authorLogic = authorLogic;
            _authorsAndBooksLogic = authorsAndBooksLogic;
            _listGenreLogic = listGenreLogic;
            _genreLogic = genreLogic;
            _mapper = mapper;  
        }

        public BookController()
        {
        }

        public ActionResult AllBooks()
        {
            ViewData["ph"] = _mapper.Map<List<PublishingHouseModel>>(_publishingHouseLogic.GetAll());
            return View(_mapper.Map<List<BookModel>>(_bookLogic.GetAll()));
        }

        public ActionResult AddBook()
        {
            string title = Request.Form["title"];
            int year = Convert.ToInt32(Request.Form["year"]);
            int ph = Convert.ToInt32(_publishingHouseLogic.GetAll().Find(house => house.PublishingHouseTitle == Request.Form["ph"]).PublishingHouseID);
            string language = Request.Form["language"];
            _bookLogic.Create(new Book(title, year, ph, language));
            return RedirectToAction("AllBooks");
        }

        public ActionResult DeleteBook(int bookId)
        {
            _bookLogic.Delete(bookId);
            return RedirectToAction("AllBooks");
        }

        public ActionResult GetBook(int bookId)
        {
            Book book = _bookLogic.GetById(bookId);
            List<AuthorsAndBooks> authorId = _authorsAndBooksLogic.GetAll().FindAll(ab => ab.BookID == bookId);
            List<Author> authors = _authorLogic.GetAll().FindAll(a => authorId.Exists(ab => ab.AuthorID == a.AuthorID));
            List<ListGenre> listGenres = _listGenreLogic.GetAll().FindAll(lg => lg.BookID == bookId);
            List<Genre> genres = _genreLogic.GetAll().FindAll(g => listGenres.Exists(lg => lg.GenreID == g.GenreID));
            ViewData["ph"] = _publishingHouseLogic.GetAll().Find(p => p.PublishingHouseID == book.PublishingHouseID)
                .PublishingHouseTitle;
            ViewData["author"] = string.Join(", ", authors.Select(a => a.AuthorFullName).ToArray());
            ViewData["genre"] = string.Join(", ", genres.Select(g => g.GenreTitle).ToArray());
            ;
            return View(_mapper.Map<BookModel>(book));
        }
    }
}

WebApplication/Controllers/BookIssuanceController.cs
using BookBLL;
using BookCopyBLL;
using BookIssuanceBLL;
using Entities;
using ReadersBLL;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AbstractBLL;
using AutoMapper;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class BookIssuanceController : Controller
    {
        private readonly IBookIssuanceLogic _issuanceLogic;
        private readonly IBookLogic _bookLogic;
        private readonly IReadersLogic _readersLogic;
        private readonly IBookCopyLogic _bookCopyLogic;
        
        private readonly IMapper _mapper;

        public BookIssuanceController(IBookLogic bookLogic, IBookIssuanceLogic bookIssuanceLogic,
            IReadersLogic readersLogic, IBookCopyLogic bookCopyLogic, IMapper mapper)
        {
            _bookLogic = bookLogic;
            _issuanceLogic = bookIssuanceLogic;
            _readersLogic = readersLogic;
            _bookCopyLogic = bookCopyLogic;
            _mapper = mapper;
        }

        public BookIssuanceController()
        {
        }

        public ActionResult ReaderBookIssuance(int libraryCard)
        {
            TempData["FullName"] = _readersLogic.GetById(libraryCard).ReaderFullName;
            TempData["LibraryCard"] = libraryCard;
            List<BookCopyTitleModel> bookCopyModels = new List<BookCopyTitleModel>();
            List<BookCopy> bookCopies = _bookCopyLogic.GetAll();
            List<Book> books = _bookLogic.GetAll();
            foreach (BookCopy bc in bookCopies)
            {
                Book book = books.Find(b => b.BookID == bc.BookID);
                bookCopyModels.Add(new BookCopyTitleModel(bc.BookCopyID, book.BookID, book.BookTitle));
            }

            TempData["BookCopy"] = bookCopyModels;

            TempData["BookIssuance"] = _mapper.Map<List<BookIssuanceModel>>(_issuanceLogic.GetAll().FindAll(bi => bi.LibraryCard == libraryCard));
            return RedirectToAction("GetBookIssuance");
        }

        public ActionResult AddBookIssuance(DateTime dateOfIssue, DateTime dateOfCompletion, int bookCopyId)
        {
            Console.WriteLine(_issuanceLogic.Create(new BookIssuance(dateOfIssue, dateOfCompletion,
                (int) TempData.Peek("LibraryCard"), bookCopyId)));
            return RedirectToAction("ReaderBookIssuance", new {libraryCard = (int) TempData["LibraryCard"]});
        }

        public ActionResult DeleteBookIssuance(int libraryCard, int id)
        {
            Console.WriteLine(_issuanceLogic.Delete(id));
            return RedirectToAction("ReaderBookIssuance", new {libraryCard});
        }

        // public ActionResult FindReader(int bookIssuanceId)
        // {
        //     
        // }

        public ActionResult GetBookIssuance()
        {
            return View(TempData["BookIssuance"]);
        }
    }
}

WebApplication/Controllers/FineController.cs
using Entities;
using FineBLL;
using System;
using System.Collections.Generic;
using System.Web.Mvc;
using AbstractBLL;
using AutoMapper;
using WebApplication.Models;

namespace WebApplication.Controllers
{
    public class FineController : Controller
    {
        private readonly IFineLogic _fineLogic;
        
        private readonly IMapper _mapper;

        public FineController()
        {
        }

        public FineController(IFineLogic fineLogic, IMapper mapper)
        {
            _fineLogic = fineLogic;
            _mapper = mapper;  
        }

        public ActionResult GetFine(int bookIssuanceId)
        {
            TempData["BookIssuanceId"] = bookIssuanceId;
            List<Fine> fineList = _fineLogic.GetAll().FindAll(f => f.BookIssuanceID == bookIssuanceId);
            return View(_mapper.Map<List<FineModel>>(fineList));
        }

        public ActionResult AddFine(int amount, string article)
        {
            _ = _fineLogic.Create(new Fine( (int)TempData.Peek("BookIssuanceID"), (int)amount));
            return RedirectToAction("GetFine", new { bookIssuanceId = TempData.Peek("BookIssuanceID") });
        }

        public ActionResult DeleteFine(int id)
        {
            _fineLogic.Delete(id);
            return RedirectToAction("GetFine", new { bookIssuanceId = TempData["BookIssuanceID"] });
        }
    }
}

WebApplication/Views/BookIssuance/GetBookIssuance.cshtml
@using WebApplication.Models
@model List<BookIssuanceModel>

@{
    ViewBag.Title = "Выдачи книг";
    ViewBag.IsAdmin = (string) TempData.Peek("login") == "admin";
    if (ViewBag.IsAdmin)
    {
        Layout = "~/Views/Shared/_LayoutAdmin.cshtml";
    }
    var books = (List<WebApplication.Models.BookCopyTitleModel>) TempData.Peek("BookCopy");

}

<h4>Выдачи пользователя: @TempData.Peek("FullName")</h4>
@if (ViewBag.IsAdmin)
{
    <div class="card">
        <form action="/BookIssuance/AddBookIssuance" method="post">
            <div class="form-row">
                <div class="form-group col-2">
                    <label for="dateOfIssue">Дата выдачи</label>
                    <input class="form-control" type="date" required="required" id="dateOfIssue" name="dateOfIssue">
                </div>
                <div class="form-group col-2">
                    <label for="dateOfCompletion">Дата сдачи</label>
                    <input class="form-control" type="date" required="required" id="dateOfCompletion" name="dateOfCompletion">
                </div>
                <div class="form-group col-3">
                    <label for="bookCopy">Экземпляр книги</label>
                    <select id="bookCopy" class="custom-select" name="bookCopyId">
                        @foreach (var bcm in books)
                        {
                            <option value="@bcm.Id">@bcm.BookTitle (#@bcm.Id)</option>
                        }
                    </select>
                </div>
                <div class="col-2 mx-auto my-auto">
                    <button class="btn btn-success" type="submit">Добавить выдачу</button>
                </div>
            </div>
        </form>
    </div>
}
<div class="row row-cols-1 row-cols-md-4">
    @foreach (var r in Model)
    {
        <div class="col mb-4">
            <div class="card">
                <div class="card-body">
                    <h5 class="card-title">@Html.ActionLink(@books.Find(b => b.Id == r.BookCopyID).BookTitle, "GetBook", "Book", new {bookId = @books.Find(b => b.Id == r.BookCopyID).BookId}, new {@class = "card-link"})</h5>
                    <h6 class="card-subtitle mb-2 text-muted">@r.BookCopyID</h6>
                    <p class="card-text">Дата выдачи: @r.DateOfIssue</p>
                    <p class="card-text">Дата сдачи: @r.DateOfCompletion</p>
                    @Html.ActionLink("Штрафы", "GetFine", "Fine", new {bookIssuanceID = @r.BookIssuanceID}, new {@class = "card-link"})
                    @if (ViewBag.IsAdmin)
                    {
                        @Html.ActionLink("Удалить", "DeleteBookIssuance", "BookIssuance", new {libraryCard = @r.LibraryCard, id = @r.BookIssuanceID}, new {@class = "card-link"})
                    }
                </div>
            </div>
        </div>
    }
</div>